{
 "title": "快充曲线统计",
 "tags": [ "battery" ],
 "time": { "from": "now-1M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT name AS __text, id AS __value FROM cars ORDER BY display_priority ASC, name ASC;"
   },
   {
    "name": "base_url",
    "query": "select base_url from settings limit 1;"
   },
   { "name": "filter_power_from", "label": "Power >=", "query": "0" },
   { "name": "filter_power_to", "label": "Power <=", "query": "260" },
   { "name": "filter_soc_from", "label": "SOC >=", "query": "0" },
   { "name": "filter_soc_to", "label": "SOC <=", "query": "100" }
  ]
 },
 "panels": [
  {
   "title": "超级充电曲线",
   "type": "xychart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  c.battery_level as \"SOC [%]\",\r\n  round(avg(c.charger_power), 0) as \"Power [kW]\",\r\n  c.charging_process_id as \"charging_process_id\",\r\n  COALESCE(g.name, a.name) || ' ' || to_char(c.date, 'YYYY-MM-dd') as \"Charge\",\r\n  p.start_date as \"start_date\",\r\n  p.end_date as \"end_date\"\r\nFROM\r\n  charges c\r\nJOIN charging_processes p ON p.id = c.charging_process_id \r\nJOIN addresses a ON a.id = p.address_id\r\nLEFT JOIN geofences g ON g.id = p.geofence_id\r\nWHERE\r\n  $__timeFilter(date)\r\n AND p.car_id::text = ANY(string_to_array('${car_id:csv}', ','))\r\n AND c.battery_level >= COALESCE(NULLIF('$filter_soc_from', '')::numeric, 0) AND c.battery_level <= COALESCE(NULLIF('$filter_soc_to', '')::numeric, 1000000000)\r\n AND charger_power >= COALESCE(NULLIF('$filter_power_from', '')::numeric, 0) AND charger_power <= COALESCE(NULLIF('$filter_power_to', '')::numeric, 1000000000)\r\n AND c.fast_charger_present\r\n AND COALESCE(g.name, a.name) ILIKE '%supercharger%' \r\nGROUP BY c.battery_level, c.charging_process_id, a.name, g.name, p.start_date, p.end_date, to_char(c.date, 'YYYY-MM-dd')"
    },
    {
     "rawSql": "SELECT\n  c.battery_level as \"B - SOC [%]\",\n  PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY charger_power) as \"B - Avg Power [kW]\"\nFROM\n  charges c\nJOIN charging_processes p ON p.id = c.charging_process_id \nJOIN addresses a ON a.id = p.address_id\nLEFT JOIN geofences g ON g.id = p.geofence_id\nWHERE\n  $__timeFilter(date)\n AND p.car_id::text = ANY(string_to_array('${car_id:csv}', ','))\n AND c.battery_level >= COALESCE(NULLIF('$filter_soc_from', '')::numeric, 0) AND c.battery_level <= COALESCE(NULLIF('$filter_soc_to', '')::numeric, 1000000000)\n AND charger_power >= COALESCE(NULLIF('$filter_power_from', '')::numeric, 0) AND charger_power <= COALESCE(NULLIF('$filter_power_to', '')::numeric, 1000000000)\n AND c.fast_charger_present\n AND COALESCE(g.name, a.name) ILIKE '%supercharger%' \nGROUP BY battery_level"
    }
   ]
  },
  {
   "title": "其他直流充电曲线",
   "type": "xychart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  c.battery_level as \"SOC [%]\",\r\n  round(avg(c.charger_power), 0) as \"Power [kW]\",\r\n  c.charging_process_id as \"charging_process_id\",\r\n  COALESCE(g.name, a.name) || ' ' || to_char(c.date, 'YYYY-MM-dd') as \"Charge\",\r\n  p.start_date as \"start_date\",\r\n  p.end_date as \"end_date\"\r\nFROM\r\n  charges c\r\nJOIN charging_processes p ON p.id = c.charging_process_id \r\nJOIN addresses a ON a.id = p.address_id\r\nLEFT JOIN geofences g ON g.id = p.geofence_id\r\nWHERE\r\n  $__timeFilter(date)\r\n AND p.car_id::text = ANY(string_to_array('${car_id:csv}', ','))\r\n AND c.battery_level >= COALESCE(NULLIF('$filter_soc_from', '')::numeric, 0) AND c.battery_level <= COALESCE(NULLIF('$filter_soc_to', '')::numeric, 1000000000)\r\n AND charger_power >= COALESCE(NULLIF('$filter_power_from', '')::numeric, 0) AND charger_power <= COALESCE(NULLIF('$filter_power_to', '')::numeric, 1000000000)\r\n AND c.fast_charger_present\r\n AND COALESCE(g.name, a.name) NOT ILIKE '%supercharger%' \r\nGROUP BY c.battery_level, c.charging_process_id, a.name, g.name, p.start_date, p.end_date, to_char(c.date, 'YYYY-MM-dd')"
    },
    {
     "rawSql": "SELECT\n  c.battery_level as \"B - SOC [%]\",\n  PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY charger_power) as \"B - Avg Power [kW]\"\nFROM\n  charges c\nJOIN charging_processes p ON p.id = c.charging_process_id \nJOIN addresses a ON a.id = p.address_id\nLEFT JOIN geofences g ON g.id = p.geofence_id\nWHERE\n  $__timeFilter(date)\n AND p.car_id::text = ANY(string_to_array('${car_id:csv}', ','))\n AND c.battery_level >= COALESCE(NULLIF('$filter_soc_from', '')::numeric, 0) AND c.battery_level <= COALESCE(NULLIF('$filter_soc_to', '')::numeric, 1000000000)\n AND charger_power >= COALESCE(NULLIF('$filter_power_from', '')::numeric, 0) AND charger_power <= COALESCE(NULLIF('$filter_power_to', '')::numeric, 1000000000)\n AND c.fast_charger_present\n AND COALESCE(g.name, a.name) NOT ILIKE '%supercharger%' \nGROUP BY battery_level"
    }
   ]
  },
  { "title": "快充会话", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "type": "piechart",
   "description": "This dashboard is meant to have a look of the charging curve sessions on Tesla Supercharges or other Fast Charging Station.\n\nAlso, you can see number of fast charging sessions you've done on each type of chargers and the count of max power (kW) reached on a session.",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH charges_summary AS (\n    SELECT\n        cp.id,\n        COALESCE(geo.name, CONCAT_WS(', ', COALESCE(addr.name, nullif(CONCAT_WS(' ', addr.road, addr.house_number), '')), addr.city)) AS location,\n        COUNT(c.charging_process_id)\n    FROM\n        charging_processes cp\n    LEFT JOIN \n        addresses addr ON addr.id = address_id\n    LEFT JOIN\n        geofences geo ON geo.id = geofence_id\n    LEFT JOIN\n        charges c ON cp.id = c.charging_process_id\n    WHERE\n        $__timeFilter(date) AND\n        cp.car_id::text = ANY(string_to_array('${car_id:csv}', ',')) AND cp.charge_energy_added > 0.01 AND c.fast_charger_present \n    GROUP BY 1, 2\n)\nSELECT \n    CASE\n        WHEN location ILIKE '%supercharger%' THEN 'Tesla Supercharger'\n        ELSE 'Other DC Stations' END AS location,\n    COUNT(location) AS n\nFROM charges_summary\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "最大功率",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 15 },
   "targets": [
    {
     "rawSql": "WITH power_summary AS (\n    SELECT ROUND(MAX(charges.charger_power) / 5, 0) * 5 AS \"power\"\n    FROM charging_processes\n    LEFT JOIN charges ON charging_processes.id = charges.charging_process_id\n    WHERE $__timeFilter(date) AND charging_processes.car_id::text = ANY(string_to_array('${car_id:csv}', ',')) AND charging_processes.charge_energy_added > 0.01 AND charges.fast_charger_present\n    GROUP BY charging_processes.id\n)\nSELECT power_summary.power AS \"Power [kW]\", COUNT(power_summary.power) AS n\nFROM power_summary\nWHERE power_summary.power >= COALESCE(NULLIF('$filter_power_from', '')::numeric, 0) AND power_summary.power <= COALESCE(NULLIF('$filter_power_to', '')::numeric, 1000000000)\nGROUP BY 1\nORDER BY 1 DESC\n"
    }
   ]
  }
 ]
}