{
 "title": "充电详情",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "charging_process_id", "query": "NULL" },
   {
    "name": "temp_unit",
    "query": "select unit_of_temperature from settings limit 1;"
   },
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT\n    id as __value,\n    CASE WHEN COUNT(id) OVER (PARTITION BY name) > 1 AND name IS NOT NULL THEN CONCAT(name, ' - ', RIGHT(vin, 6)) ELSE COALESCE(name, CONCAT('VIN ', vin)) end as __text \nFROM cars\nORDER BY display_priority ASC, name ASC, vin ASC;"
   },
   {
    "name": "map_url",
    "label": "选择地图源",
    "query": "高德地图 : https://wprd0{1-4}.is.autonavi.com/appmaptile?lang=zh_CN&size=1&style=7&scl=1&x={x}&y={y}&z={z}, 腾讯地图 : https://rt{0-3}.map.gtimg.com/tile?z={z}&x={x}&y={-y}&type=vector&styleid=0"
   },
   {
    "name": "length_unit",
    "query": "select unit_of_length from settings limit 1;"
   },
   {
    "name": "preferred_range",
    "query": "select preferred_range from settings limit 1;"
   },
   {
    "name": "base_url",
    "query": "select base_url from settings limit 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "充电详情",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(date),\n  battery_level,\n  charger_power,\n  (case when battery_heater_on then 10 when battery_heater then 10 else 0 end) as battery_heater,\n  convert_km(${preferred_range}_battery_range_km, '$length_unit') as range_$length_unit,\n  charger_voltage,\n  (case when charger_phases = 2 then 3 when charger_phases = 1 then 1 else 0 end) as charger_phases,\n  charger_actual_current,\n  charger_pilot_current,\n  convert_celsius(outside_temp, '$temp_unit') outside_temp_$temp_unit\nFROM\n  charges c\njoin\n  charging_processes p ON p.id = c.charging_process_id \nWHERE\n  $__timeFilter(date)\n AND p.car_id::text = ANY(string_to_array('${car_id:csv}', ','))\nORDER BY\n  date ASC"
    }
   ]
  },
  {
   "title": "费用",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cost from charging_processes where id::text = ANY(string_to_array('${charging_process_id:csv}', ','));"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(g.name, CONCAT_WS(', ', COALESCE(addresses.name, CONCAT_WS(' ', addresses.road, addresses.house_number)), addresses.city))\nFROM\n\tcharging_processes c\n\tLEFT JOIN addresses ON addresses.id = c.address_id\n\tLEFT JOIN geofences g ON g.id = geofence_id\nWHERE\n\tc.id::text = ANY(string_to_array('${charging_process_id:csv}', ','))"
    }
   ]
  },
  {
   "title": "充电量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  coalesce(cp_added, c_added) AS \"Added\"\r\nFROM (SELECT cp.charge_energy_added AS cp_added from charging_processes cp where id::text = ANY(string_to_array('${charging_process_id:csv}', ','))) cp\r\nCROSS JOIN (SELECT max(charge_energy_added) AS c_added FROM charges WHERE charging_process_id::text = ANY(string_to_array('${charging_process_id:csv}', ','))) c"
    },
    {
     "rawSql": "SELECT  charge_energy_used AS \"Used\"\r\nFROM  charging_processes where id::text = ANY(string_to_array('${charging_process_id:csv}', ','))"
    },
    {
     "rawSql": "SELECT  CASE WHEN charge_energy_used IS NULL THEN NULL ELSE LEAST(charge_energy_added / NULLIF(charge_energy_used, 0), 1.0) * 100 END AS \"Efficiency\"\r\nFROM  charging_processes where id::text = ANY(string_to_array('${charging_process_id:csv}', ','))"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n    $__time(date),\n    unnest(ARRAY[gcj_lat, gcj_lat]) AS latitude,\n    unnest(ARRAY[gcj_lon, gcj_lon]) AS longitude\nFROM\n    charging_processes c\n    JOIN positions p ON c.position_id = p.id\nWHERE\n    $__timeFilter(date)\n    AND c.car_id::text = ANY(string_to_array('${car_id:csv}', ','))\n    AND gcj_lat IS NOT NULL\n    AND gcj_lon IS NOT NULL"
    }
   ]
  },
  {
   "title": "电池电量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT start_battery_level AS \"Start\" FROM  charging_processes WHERE id::text = ANY(string_to_array('${charging_process_id:csv}', ','))"
    },
    {
     "rawSql": "SELECT end_battery_level - start_battery_level AS \"Added\" FROM  charging_processes WHERE id::text = ANY(string_to_array('${charging_process_id:csv}', ','))"
    },
    {
     "rawSql": "SELECT end_battery_level AS \"End\" FROM  charging_processes WHERE id::text = ANY(string_to_array('${charging_process_id:csv}', ','))\r\n"
    }
   ]
  },
  {
   "title": "平均功率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(date,$__interval),\r\navg(\r\n    case when charger_phases >= 1 then (\r\n        case when charger_phases = 2 then 3 when charger_phases = 1 then 1 else 0 end)\r\n    * charger_actual_current * charger_voltage / 1000.0 else charger_power end) as \"Power\" \r\nFROM charges WHERE charging_process_id::text = ANY(string_to_array('${charging_process_id:csv}', ','))\r\nGROUP BY 1 ORDER BY 1 "
    }
   ]
  },
  {
   "title": "车外平均温度",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(date,$__interval),\r\nconvert_celsius(avg(outside_temp), '$temp_unit') as outside_temp_$temp_unit \r\nFROM charges WHERE charging_process_id::text = ANY(string_to_array('${charging_process_id:csv}', ','))\r\nGROUP BY 1 ORDER BY 1 "
    }
   ]
  },
  {
   "title": "续航里程 ($preferred_range)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT convert_km(start_${preferred_range}_range_km, '$length_unit') AS start_$length_unit FROM charging_processes WHERE id::text = ANY(string_to_array('${charging_process_id:csv}', ',')) "
    },
    {
     "rawSql": "SELECT convert_km(end_${preferred_range}_range_km - start_${preferred_range}_range_km, '$length_unit') AS added_$length_unit FROM charging_processes WHERE id::text = ANY(string_to_array('${charging_process_id:csv}', ',')) "
    },
    {
     "rawSql": "SELECT convert_km(end_${preferred_range}_range_km, '$length_unit') AS end_$length_unit FROM charging_processes WHERE id::text = ANY(string_to_array('${charging_process_id:csv}', ','))"
    }
   ]
  },
  {
   "title": "充电曲线",
   "type": "xychart",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  battery_level as \"SOC [%]\",\n  charger_power as \"Power [kW]\"\nFROM\n  charges c\njoin\n  charging_processes p ON p.id = c.charging_process_id \nWHERE\n  $__timeFilter(date)\n AND p.car_id::text = ANY(string_to_array('${car_id:csv}', ','))\n AND charger_power > 0\nORDER BY\n  date ASC"
    },
    {
     "rawSql": "SELECT\n  battery_level as \"SOC [%]\",\n  avg(charger_power) as \"Power [kW]\"\nFROM\n  charges c\njoin\n  charging_processes p ON p.id = c.charging_process_id \nWHERE\n  $__timeFilter(date)\n AND p.car_id::text = ANY(string_to_array('${car_id:csv}', ','))\n AND charger_power > 0\nGROUP BY\n  battery_level, fast_charger_present\nORDER BY\n  battery_level ASC  "
    }
   ]
  }
 ]
}