{
 "title": "当前充电状态",
 "tags": [ "battery" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT name AS __text, id AS __value FROM cars ORDER BY display_priority ASC, name ASC;"
   },
   {
    "name": "length_unit",
    "query": "select unit_of_length from settings limit 1;"
   },
   {
    "name": "temp_unit",
    "query": "select unit_of_temperature from settings limit 1;"
   },
   {
    "name": "BatteryCapacity",
    "query": "SELECT AVG(Capacity) AS CurrentCapacity FROM\n  (SELECT (100.0 * cp.charge_energy_added) / (GREATEST(1,MAX(usable_battery_level) - MIN(usable_battery_level))) AS Capacity\t\n    FROM charging_processes cp\n\t  INNER JOIN charges c ON cp.id = c.charging_process_id\n\t  WHERE cp.car_id::text = ANY(string_to_array('${car_id:csv}', ',')) AND \n            cp.charge_energy_added >= (SELECT efficiency FROM cars WHERE id = 1) * 100.0\n    GROUP BY  cp.charge_energy_added, cp.end_date\n    ORDER BY cp.end_date DESC \n    LIMIT 5) AS lastEstimatedCapacity;"
   },
   {
    "name": "current_charge_time",
    "query": "SELECT (round(extract(epoch FROM start_date) - 10) * 1000) AS start_date_ts FROM charging_processes WHERE id::text = ANY(string_to_array('${charging_processes:csv}', ','))"
   },
   {
    "name": "charging_processes",
    "query": "SELECT id FROM charging_processes WHERE car_id::text = ANY(string_to_array('${car_id:csv}', ',')) ORDER BY start_date DESC LIMIT 1"
   },
   {
    "name": "current_end_time",
    "query": "SELECT CASE WHEN end_date IS NULL THEN 'now&refresh=10s' ELSE CAST(round(extract(epoch FROM end_date) - 10) * 1000 AS VARCHAR(100)) END FROM charging_processes WHERE id::text = ANY(string_to_array('${charging_processes:csv}', ','))"
   }
  ]
 },
 "panels": [
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "%",
     "rawSql": "SELECT battery_level as \"SOC [%]\" FROM charges c join charging_processes p ON p.id = c.charging_process_id WHERE $__timeFilter(date) AND p.car_id::text = ANY(string_to_array('${car_id:csv}', ',')) ORDER BY c.ID DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "%",
     "rawSql": "SELECT battery_level * COALESCE(NULLIF('$BatteryCapacity', '')::numeric, 0) / 100 as \"kWh\", COALESCE(NULLIF('$BatteryCapacity', '')::numeric, 0) AS Total FROM charges c join charging_processes p ON p.id = c.charging_process_id WHERE $__timeFilter(date) AND p.car_id::text = ANY(string_to_array('${car_id:csv}', ',')) ORDER BY c.ID DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "text",
   "description": "Load this dashboard to while you are in a charging session. When you open this dashboard it will show the last 15 minutes, but you should click the \"Current Charge\" button at the top right corner, to enter in Kiosk mode:\n\n- If you are charging, you will see the information from the start time of the current charge session until now and it will refesh automatically every 30 seconds.\n\n- If you are just browsing (not charging) you will see the information of the last charge session.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": {
    "content": "<center>\n<img src=\"https://raw.githubusercontent.com/jheredianet/Teslamate-CustomGrafanaDashboards/main/screenshots/help/BatteryCharging.gif\"\nstyle=\"max-height: 125px\" />\n</center>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  start_date AS \"time\",\n  start_km\nFROM drives\nWHERE\n  $__timeFilter(start_date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "充电量",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "kWh Added",
     "rawSql": "SELECT $__timeGroupAlias(date,$__interval), avg(charge_energy_added) as \"Added\" FROM charges WHERE charging_process_id::text = ANY(string_to_array('${charging_processes:csv}', ',')) AND $__timeFilter(date) GROUP BY 1 "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE(g.name, CONCAT_WS(', ', COALESCE(addresses.name, CONCAT_WS(' ', addresses.road, addresses.house_number)), addresses.city)) FROM \tcharging_processes c \tLEFT JOIN addresses ON addresses.id = c.address_id \tLEFT JOIN geofences g ON g.id = geofence_id WHERE \tc.id::text = ANY(string_to_array('${charging_processes:csv}', ','))"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "alias": "Power [kW]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "rawSql": "SELECT $__time(date), battery_level as \"SOC [%]\", (case when charger_phases >= 1 then (case when charger_phases = 2 then 3 when charger_phases = 1 then 1 else 0 end) * charger_actual_current * charger_voltage / 1000.0 else charger_power end) as \"Power [kW]\", (case when battery_heater_on then 10 when battery_heater then 10 else 0 end) as \"Battery heater\" FROM charges c JOIN charging_processes p ON p.id = c.charging_process_id WHERE $__timeFilter(date) and p.car_id::text = ANY(string_to_array('${car_id:csv}', ',')) ORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "alias": "Real",
     "measurement": "km",
     "rawSql": " SELECT battery_level as \"初始电量\" FROM charges \twhere charging_process_id::text = ANY(string_to_array('${charging_processes:csv}', ',')) \tORDER BY DATE ASC \tLIMIT 1"
    },
    {
     "rawSql": "SELECT battery_level - (SELECT battery_level as \"Added\" FROM charges where charging_process_id::text = ANY(string_to_array('${charging_processes:csv}', ','))\tORDER BY DATE ASC \tLIMIT 1) as \"充入电量\" FROM charges c join charging_processes p ON p.id = c.charging_process_id WHERE $__timeFilter(date) AND p.car_id::text = ANY(string_to_array('${car_id:csv}', ',')) ORDER BY c.ID DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "充电时间",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Elapsed Time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "WITH start_process AS ( SELECT date FROM charges \twhere charging_process_id::text = ANY(string_to_array('${charging_processes:csv}', ',')) \tORDER BY DATE ASC \tLIMIT 1 ) SELECT EXTRACT(EPOCH FROM (charges.date - start_process.date)) AS \"Elapsed\" FROM charges, start_process WHERE charging_process_id::text = ANY(string_to_array('${charging_processes:csv}', ',')) AND $__timeFilter(charges.date) order by charges.date desc LIMIT 1"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n    $__time(date),\n    gcj_lat AS latitude,\n    gcj_lon AS longitude\nFROM positions\nWHERE\n    car_id::text = ANY(string_to_array('${car_id:csv}', ','))\n    AND $__timeFilter(date)\n    AND gcj_lat IS NOT NULL\n    AND gcj_lon IS NOT NULL\nORDER BY\n    date ASC"
    }
   ]
  },
  {
   "title": "里程表",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Km" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "alias": "Real",
     "measurement": "km",
     "rawSql": "select $__time(date), convert_km(odometer::numeric, '$length_unit') as \"Odometer\" from positions where car_id::text = ANY(string_to_array('${car_id:csv}', ',')) order by date desc limit 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Real",
     "measurement": "km",
     "rawSql": "SELECT $__timeGroupAlias(date,$__interval), avg(convert_km(rated_battery_range_km, '$length_unit')) as \"初始续航\" FROM charges WHERE charging_process_id::text = ANY(string_to_array('${charging_processes:csv}', ',')) AND $__timeFilter(date) GROUP BY 1 ORDER BY 1 asc limit 1"
    },
    {
     "alias": "Real",
     "measurement": "km",
     "rawSql": "SELECT $__timeGroupAlias(date,$__interval), avg(convert_km(rated_battery_range_km, '$length_unit')) as \"表显续航\" FROM charges WHERE charging_process_id::text = ANY(string_to_array('${charging_processes:csv}', ',')) AND $__timeFilter(date) GROUP BY 1 ORDER BY 1 desc limit 1"
    },
    {
     "alias": "Estimated",
     "measurement": "km",
     "rawSql": "SELECT $__timeGroupAlias(date,$__interval), avg(convert_km(est_battery_range_km, '$length_unit')) as \"预估续航\" FROM positions WHERE $__timeFilter(date) GROUP BY 1 ORDER BY 1 desc limit 1"
    }
   ]
  },
  {
   "title": "电流",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(date,$__interval), avg(case when charger_voltage > 2 then charger_actual_current else ((2.85 + (usable_battery_level * 0.013)) * 96) * charger_power / 100 end) as \"Current\" FROM charges WHERE charging_process_id::text = ANY(string_to_array('${charging_processes:csv}', ',')) AND $__timeFilter(date) GROUP BY 1 ORDER BY 1 "
    }
   ]
  },
  {
   "title": "电压",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(date,$__interval), avg(case when charger_voltage > 2 then charger_voltage else charger_power / GREATEST(0.1, (((2.85 + (usable_battery_level * 0.013)) * 96.0) * charger_power / 100.0)) * 1000.0 end) as \"Volt\" FROM charges WHERE charging_process_id::text = ANY(string_to_array('${charging_processes:csv}', ',')) AND $__timeFilter(date) GROUP BY 1 ORDER BY 1 "
    }
   ]
  },
  {
   "title": "功率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(date,$__interval), avg(case when charger_phases >= 1 then (case when charger_phases = 2 then 3 when charger_phases = 1 then 1 else 0 end) * charger_actual_current * charger_voltage / 1000.0 else charger_power end) as \"Power\" FROM charges WHERE charging_process_id::text = ANY(string_to_array('${charging_processes:csv}', ',')) AND $__timeFilter(date) GROUP BY 1 ORDER BY 1 "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(date,$__interval), avg(convert_celsius(outside_temp, '$temp_unit')) as \"车外温度\" FROM charges WHERE charging_process_id::text = ANY(string_to_array('${charging_processes:csv}', ',')) AND $__timeFilter(date) GROUP BY 1 ORDER BY 1 "
    },
    {
     "rawSql": "SELECT $__timeGroupAlias(date,$__interval), avg(convert_celsius(inside_temp, '$temp_unit')) AS \"车内温度\" FROM positions WHERE car_id::text = ANY(string_to_array('${car_id:csv}', ',')) and inside_temp is not null AND $__timeFilter(date) GROUP BY 1 ORDER BY 1 "
    },
    {
     "rawSql": "SELECT \t$__timeGroupAlias(date,$__interval), \tavg(convert_celsius(driver_temp_setting, '$temp_unit')) as \"空调温度\" FROM positions WHERE driver_temp_setting IS NOT NULL AND car_id::text = ANY(string_to_array('${car_id:csv}', ',')) AND $__timeFilter(date) GROUP BY 1 ORDER BY 1 "
    }
   ]
  }
 ]
}